Repository Inkacoders/Interior-consultant, pull requests merged in 2022-04, with the labels that each got.

#5 Font files / variables
  src/assets/fonts/icomoon.eot
  src/assets/fonts/icomoon.svg
  src/assets/fonts/icomoon.ttf
  src/assets/fonts/icomoon.woff
  src/assets/fonts/lora-v23-latin-500.woff
  src/assets/fonts/lora-v23-latin-500.woff2
  src/assets/fonts/lora-v23-latin-700.woff
  src/assets/fonts/lora-v23-latin-700.woff2
  src/assets/fonts/lora-v23-latin-regular.woff
  src/assets/fonts/lora-v23-latin-regular.woff2
  src/assets/fonts/montserrat-v23-latin-500.woff
  src/assets/fonts/montserrat-v23-latin-500.woff2
  src/assets/fonts/montserrat-v23-latin-700.woff
  src/assets/fonts/montserrat-v23-latin-700.woff2
  src/assets/fonts/montserrat-v23-latin-regular.woff
  src/assets/fonts/montserrat-v23-latin-regular.woff2
  src/css/fonts.css
  src/css/variables.css
  src/js/index.js
Labels: component

#7 Card component added
  package-lock.json
  public/index.html
  src/assets/images/author-1x.png
  src/assets/images/author-2x.png
  src/assets/images/photo2.png
  src/css/atom-author.css
  src/css/fonts.css
  src/css/mole-card.css
  src/css/variables.css
  src/js/index.js
Labels: Feature

#6 Feat/navbar
  package-lock.json
  public/index.html
  src/css/fonts.css
  src/css/menu-item.css
  src/js/index.js
Labels: Feature, Section
